### ISSUE TITLE
what is 3. label?

### ISSUE THREAD

**Issue by fatiherbag** [mj129/Surveillance-of-neonatal-jaundice#1]

**Comment by mj129** [comment]
Sorry, can you describe the issue in more detail?

**Comment by fatiherbag** [comment]
There are 3 class label when prediction. We know that first one and second but what is the third class label?

**Comment by mj129** [comment]
We classify the newborns into three categories according to total serum bilirubin (TSB): newborns with a TSB < 5 mg/dL, newborns with a TSB ≥ 5 mg/dL and a TSB ≤ 17 mg/dL, and those with a TSB > 17 mg/dL.

**Comment by fatiherbag** [comment]
Thanks.By the way how can i find the dataset.

**Comment by mj129** [comment]
Our paper has not been officially published, so the dataset has not been opened yet.
